"use client";
import { useState } from "react";
import { Send } from "lucide-react";
import { proxyApi } from "@/lib/client-api";

export function NotificationForm() {
  const [form, setForm] = useState({ title: "", message: "", type: "info", audience: "all" });
  const [status, setStatus] = useState(""); const [sending, setSending] = useState(false);
  const field = "w-full rounded-xl border border-(--color-border) bg-white px-3 py-2 text-sm outline-none focus:border-(--color-burgundy)";
  const send = async () => { setSending(true); setStatus(""); try { const result = await proxyApi.post<{ sent: number; failed: number }>("/admin/notifications", form); setStatus(`Delivered to ${result.sent} device${result.sent === 1 ? "" : "s"}${result.failed ? `; ${result.failed} failed` : ""}.`); setForm((current) => ({ ...current, title: "", message: "" })); } catch (error) { setStatus(error instanceof Error ? error.message : "Could not send notification"); } finally { setSending(false); } };
  return <div className="rounded-2xl border border-(--color-border) bg-white p-5"><div className="grid gap-4 sm:grid-cols-2"><label className="text-xs font-bold uppercase text-(--color-text-muted)">Audience<select className={`mt-1 ${field}`} value={form.audience} onChange={(e) => setForm({ ...form, audience: e.target.value })}><option value="all">All users</option><option value="free">Free users</option><option value="pro">Pro users</option></select></label><label className="text-xs font-bold uppercase text-(--color-text-muted)">Type<select className={`mt-1 ${field}`} value={form.type} onChange={(e) => setForm({ ...form, type: e.target.value })}><option value="info">Information</option><option value="promotion">Promotion</option><option value="maintenance">Maintenance</option><option value="update">Product update</option></select></label></div><label className="mt-4 block text-xs font-bold uppercase text-(--color-text-muted)">Title<input className={`mt-1 ${field}`} maxLength={100} value={form.title} onChange={(e) => setForm({ ...form, title: e.target.value })}/></label><label className="mt-4 block text-xs font-bold uppercase text-(--color-text-muted)">Message<textarea className={`mt-1 min-h-28 ${field}`} maxLength={500} value={form.message} onChange={(e) => setForm({ ...form, message: e.target.value })}/></label><button disabled={sending || !form.title.trim() || !form.message.trim()} onClick={send} className="mt-4 inline-flex items-center gap-2 rounded-xl bg-(--color-burgundy) px-5 py-2.5 text-sm font-bold text-white disabled:opacity-50"><Send size={16}/>{sending ? "Sending…" : "Send notification"}</button>{status && <p className="mt-3 text-sm text-(--color-text-muted)">{status}</p>}</div>;
}
