import type { Metadata } from "next";
import Link from "next/link";
import Image from "next/image";
import { Check } from "lucide-react";
import { MarketingLayout } from "@/components/marketing/MarketingLayout";
import { Section, SectionTitle } from "@/components/marketing/Section";
import { ReviewsSection } from "@/components/marketing/ReviewsSection";
import { FaqSection } from "@/components/marketing/FaqSection";
import { HomeHeroVisuals } from "@/components/marketing/HomeHeroVisuals";
import { HomeToolUpload } from "@/components/marketing/HomeToolUpload";
import { GooglePlayBadge } from "@/components/marketing/GooglePlayBadge";
import { SoftwareApplicationJsonLd, FaqJsonLd } from "@/components/seo/JsonLd";
import { isSignedIn } from "@/lib/is-signed-in";
import { toolForSlug } from "@/lib/tools";
import { SITE_URL } from "@/lib/site";

const TITLE = "Verified Glam - Beauty Scanner | AI Beauty Insights from Your Selfie";
const DESCRIPTION = "Verified Glam - Beauty Scanner analyzes your selfie for face beauty scores, symmetry, celebrity look-alikes, and personalized glow-up tips.";
export const metadata: Metadata = { title: TITLE, description: DESCRIPTION, alternates: { canonical: SITE_URL }, openGraph: { title: TITLE, description: DESCRIPTION, url: SITE_URL } };

const HERO_BULLETS = ["10 scan types, from face beauty to color analysis", "Results on your photo with face overlays and clear scores", "Free tier with optional Pro for full features and no ads", "Your photos are processed securely on our servers, never with on-device API keys"];
const PRESS_LOGOS = [{ name: "Allure", file: "allure.svg" }, { name: "Vogue", file: "vogue.svg" }, { name: "Byrdie", file: "byrdie.svg" }, { name: "Cosmopolitan", file: "cosmopolitan.svg" }, { name: "Harper's Bazaar", file: "harpers-bazaar.svg" }];
const VALUE_CARDS = [{ title: "Scan in seconds", description: "Upload a selfie and get a clear camera-style scan in moments.", image: "value-scan-v2.png" }, { title: "See results on your photo", description: "See score details and landmarks presented on your own portrait.", image: "value-results-v2.png" }, { title: "Build your glow-up routine", description: "Turn one result into a simple beauty routine you can keep.", image: "value-glowup-v2.png" }];
const STATS = [{ value: "10", label: "Beauty scan types" }, { value: "AI", label: "Personalized results" }, { value: "7", label: "Day glow-up plans" }];
const FEATURE_ROWS = [
  { tool: toolForSlug("face-beauty-analysis")!, eyebrow: "Your complete score", title: "See the details behind your beauty score", description: "Start with a single clear selfie and receive an easy-to-read overview of facial balance, feature harmony, and the areas the scan recognized. Your result is presented on your own photo, so it is simple to understand and save.", image: "face-beauty-v2.png", dimensions: ["Beauty", "Symmetry", "Eyes", "Lips"] },
  { tool: toolForSlug("facial-symmetry")!, eyebrow: "Balance and proportion", title: "Understand your facial symmetry at a glance", description: "A symmetry scan maps the balance of key facial areas and turns it into a clear visual report. Use it as a thoughtful beauty reference when you are exploring makeup, hair, angles, or simply learning more about your features.", cta: "Upload your image", image: "facial-symmetry-v2.png", dimensions: ["Symmetry", "Eyes", "Brows", "Jawline"] },
  { tool: toolForSlug("celebrity-look-alike")!, eyebrow: "A fun comparison", title: "Find the celebrity traits you share", description: "Discover playful look-alike matches based on broad facial traits, then explore the facial details that shaped the result. It is a shareable entertainment feature for curiosity and conversation, never identity verification.", cta: "Upload your image", image: "celebrity-match-v2.png", dimensions: ["Matches", "Eyes", "Jawline", "Smile"] },
  { tool: toolForSlug("attractiveness-test")!, eyebrow: "Style-focused insight", title: "Explore the features that shape your look", description: "Get a light, self-discovery-focused view of photo balance, facial harmony, and style signals. The result helps you explore how different elements come together in a photo, with no medical or professional claims.", cta: "Upload your image", image: "attractiveness-v2.png", dimensions: ["Rating", "Harmony", "Style", "Photo score"] },
];
const REVIEWS = [{ name: "Amara K.", text: "I love seeing my scores right on my own photo. It feels personal, not generic.", rating: 5, avatar: "avatar-1.jpg" }, { name: "Priya S.", text: "The symmetry scan helped me understand my features in a kind, visual way. I use it before makeup routines.", rating: 5, avatar: "avatar-2.jpg" }, { name: "Elena M.", text: "Celebrity look-alike is fun to share with friends. Glow Up Guide keeps me consistent every week.", rating: 5, avatar: "avatar-3.jpg" }];
const FAQ = [{ question: "How does Verified Glam - Beauty Scanner use my photos?", answer: "You upload a selfie for the scan you choose. Your photo is sent securely to our servers for AI analysis and is connected to your account. See our Privacy Policy for details." }, { question: "Is this medical or professional advice?", answer: "No. Verified Glam - Beauty Scanner is for entertainment and beauty self-discovery. It is not medical, dermatological, or psychological advice." }, { question: "What is free vs Pro?", answer: "Free users get basic scans with ads and limited history. Pro unlocks all scan types, removes ads, and includes credits for AI generations." }, { question: "Is Verified Glam - Beauty Scanner available on iPhone?", answer: "Verified Glam - Beauty Scanner is currently available for Android on Google Play and on the web." }, { question: "How long is my data kept?", answer: "Scan photos and results are tied to your account while you use the service. You can delete your account from the app or through the account deletion page." }, { question: "Who can use the app?", answer: "Verified Glam - Beauty Scanner is for adults aged 18 and older." }];

export default async function HomePage() {
  const signedIn = await isSignedIn();
  const challenge = toolForSlug("beauty-routine-challenge")!;
  return <MarketingLayout><SoftwareApplicationJsonLd /><FaqJsonLd items={FAQ} />
    <section className="px-4 py-12 sm:px-6 sm:py-20"><div className="mx-auto grid max-w-(--max-content) items-center gap-10 lg:grid-cols-2"><div><h1 className="text-4xl font-extrabold leading-tight tracking-[-0.04em] text-(--color-burgundy-dark) sm:text-5xl">AI beauty insights from your selfie</h1><p className="mt-4 max-w-lg text-lg leading-relaxed text-(--color-text-muted)">Pretty in every way. Upload a photo, get personalized scores, symmetry breakdowns, and glow-up tips powered by AI.</p><ul className="mt-6 space-y-2.5">{HERO_BULLETS.map((bullet) => <li key={bullet} className="flex items-start gap-2.5 text-(--color-text)"><Check size={18} className="mt-0.5 shrink-0 text-(--color-burgundy)" />{bullet}</li>)}</ul><div className="mt-7 flex flex-wrap items-center gap-3"><GooglePlayBadge /><Link href="/login" className="rounded-lg bg-(--color-burgundy) px-7 py-3.5 font-semibold text-white shadow-[0_8px_18px_rgba(82,13,28,0.16)] transition-colors hover:bg-(--color-burgundy-dark)">Log in on web</Link></div></div><HomeHeroVisuals /></div></section>

    <Section tint><p className="mb-6 text-center text-sm font-semibold uppercase tracking-wide text-(--color-text-muted)">Featured on</p><div className="flex flex-wrap items-center justify-center gap-x-10 gap-y-6">{PRESS_LOGOS.map((press) => <Image key={press.name} src={`/images/press/${press.file}`} alt={press.name} width={120} height={24} className="h-6 w-auto grayscale opacity-60" />)}</div><p className="mt-4 text-center text-xs text-(--color-text-muted)">Illustrative placement. Not affiliated endorsements.</p></Section>

    <Section><SectionTitle title="Ready to discover your glow?" subtitle="Verified Glam - Beauty Scanner turns a quick selfie into actionable beauty insights, scores you can understand, tips you can use, and results you can save." /><div className="grid gap-5 sm:grid-cols-3">{VALUE_CARDS.map((card) => <div key={card.title} className="overflow-hidden rounded-2xl border border-(--color-border) bg-white text-center shadow-[0_12px_30px_rgba(82,13,28,0.05)]"><div className="relative aspect-[3/2]"><Image src={`/images/lifestyle/${card.image}`} alt={card.title} fill className="object-cover" sizes="(min-width: 640px) 33vw, 100vw" /></div><div className="p-6"><p className="font-bold text-(--color-text)">{card.title}</p><p className="mt-2 text-sm text-(--color-text-muted)">{card.description}</p></div></div>)}</div><div className="mt-10 grid grid-cols-3 gap-4 text-center">{STATS.map((stat) => <div key={stat.label}><p className="text-3xl font-extrabold text-(--color-burgundy) sm:text-4xl">{stat.value}</p><p className="mt-1 text-sm text-(--color-text-muted)">{stat.label}</p></div>)}</div></Section>

    <Section tint className="py-16 sm:py-20"><SectionTitle title="Everything you need to shine" subtitle="Choose the beauty insight you are curious about, upload one clear selfie, and continue to your secure dashboard for the full result." /><div className="space-y-16 sm:space-y-20">{FEATURE_ROWS.map((row, index) => <article key={row.title} className={`grid items-center gap-8 lg:grid-cols-2 lg:gap-14 ${index % 2 === 1 ? "lg:[&>*:first-child]:order-2" : ""}`}><div className="overflow-hidden rounded-[26px] border border-white/90 bg-white p-2 shadow-[0_20px_44px_rgba(82,13,28,0.12)] sm:p-3"><div className="relative aspect-[4/3] overflow-hidden rounded-[19px]"><Image src={`/images/features/${row.image}`} alt={`${row.title} result example`} fill className="object-cover" sizes="(min-width: 1024px) 50vw, 100vw" /></div></div><div><p className="text-xs font-extrabold uppercase tracking-[0.16em] text-(--color-burgundy)">{row.eyebrow}</p><h3 className="mt-3 text-3xl font-extrabold leading-tight tracking-[-0.04em] text-(--color-burgundy-dark) sm:text-[36px]">{row.title}</h3><p className="mt-4 max-w-xl leading-7 text-(--color-text-muted)">{row.description}</p>{index === 0 ? <HomeToolUpload tool={row.tool} isSignedIn={signedIn} dimensions={row.dimensions} /> : <Link href={`/${row.tool.slug}`} className="mt-6 inline-flex items-center gap-2 rounded-lg bg-(--color-burgundy) px-5 py-3 text-sm font-extrabold text-white shadow-[0_8px_18px_rgba(82,13,28,0.18)] transition-colors hover:bg-(--color-burgundy-dark)">Upload your image<span aria-hidden="true">→</span></Link>}</div></article>)}</div></Section>

    <Section><div className="grid items-center gap-8 rounded-[28px] border border-(--color-border) bg-white p-3 shadow-[0_16px_36px_rgba(82,13,28,0.06)] md:grid-cols-2 sm:p-4"><div className="relative aspect-[4/3] overflow-hidden rounded-[20px]"><Image src="/images/features/glow-up-challenge-v2.png" alt="Verified Glam seven-day glow-up challenge" fill className="object-cover" sizes="(min-width: 768px) 50vw, 100vw" /></div><div className="p-3 sm:p-5"><p className="text-xs font-extrabold uppercase tracking-[0.16em] text-(--color-burgundy)">A routine you can keep</p><h2 className="mt-3 text-3xl font-extrabold tracking-[-0.04em] text-(--color-burgundy-dark)">Seven-Day Glow-Up Challenge</h2><p className="mt-4 leading-7 text-(--color-text-muted)">Start with a baseline photo, choose a focus, and follow a simple daily plan that helps you stay consistent without overcomplicating your routine.</p><Link href={`/${challenge.slug}`} className="mt-6 inline-flex items-center gap-2 rounded-lg bg-(--color-burgundy) px-5 py-3 text-sm font-extrabold text-white shadow-[0_8px_18px_rgba(82,13,28,0.18)] transition-colors hover:bg-(--color-burgundy-dark)">Start your glow-up challenge<span aria-hidden="true">→</span></Link></div></div></Section>

    <ReviewsSection items={REVIEWS} /><FaqSection items={FAQ} />
    <section className="bg-(--color-burgundy-dark) px-4 py-16 text-center text-white sm:px-6"><h2 className="text-2xl font-extrabold sm:text-3xl">Download Verified Glam - Beauty Scanner</h2><p className="mx-auto mt-3 max-w-xl text-white/80">Get AI beauty insights on Android, or log in on the web to upload a photo and sync your scan history.</p><div className="mt-7 flex flex-wrap items-center justify-center gap-4"><GooglePlayBadge /><Link href="/login" className="rounded-lg border border-white/50 px-7 py-3.5 font-semibold">Log in on web</Link></div><p className="mt-6 text-xs text-white/60">Package: com.verifiedglam.beauty_scanner · Questions? support@verifiedglam.com</p></section>
  </MarketingLayout>;
}
