"use client";
import { useState } from "react";
import { Save } from "lucide-react";
import { proxyApi } from "@/lib/client-api";

export function SettingsForm({ initial }: { initial: Record<string, string> }) {
  const [values, setValues] = useState(initial); const [status, setStatus] = useState("");
  const set = (key: string, value: string) => setValues((current) => ({ ...current, [key]: value }));
  const save = async () => { setStatus("Saving…"); try { await proxyApi.put("/admin/settings", values); setStatus("Saved"); } catch (error) { setStatus(error instanceof Error ? error.message : "Save failed"); } };
  const input = "mt-1 w-full rounded-xl border border-(--color-border) bg-white px-3 py-2 text-sm outline-none focus:border-(--color-burgundy)";
  return <div className="space-y-5">
    <section className="rounded-2xl border border-(--color-border) bg-white p-5"><div className="flex items-center justify-between"><div><h2 className="font-bold">Announcement banner</h2><p className="text-xs text-(--color-text-muted)">Configure a platform-wide message.</p></div><input type="checkbox" checked={values.announcement_enabled === "true"} onChange={(e) => set("announcement_enabled", String(e.target.checked))} className="size-5 accent-(--color-burgundy)"/></div><label className="mt-4 block text-xs font-bold uppercase text-(--color-text-muted)">Message<input className={input} value={values.announcement_text ?? ""} onChange={(e) => set("announcement_text", e.target.value)}/></label><label className="mt-3 block text-xs font-bold uppercase text-(--color-text-muted)">Type<select className={input} value={values.announcement_type ?? "info"} onChange={(e) => set("announcement_type", e.target.value)}><option value="info">Info</option><option value="success">Good news</option><option value="warning">Warning</option></select></label></section>
    <section className="rounded-2xl border border-(--color-border) bg-white p-5"><div className="flex items-center justify-between"><div><h2 className="font-bold">Maintenance mode</h2><p className="text-xs text-(--color-text-muted)">Immediately blocks new AI analyses.</p></div><input type="checkbox" checked={values.maintenance_enabled === "true"} onChange={(e) => set("maintenance_enabled", String(e.target.checked))} className="size-5 accent-(--color-burgundy)"/></div><label className="mt-4 block text-xs font-bold uppercase text-(--color-text-muted)">Message<input className={input} value={values.maintenance_message ?? ""} onChange={(e) => set("maintenance_message", e.target.value)}/></label></section>
    <section className="rounded-2xl border border-(--color-border) bg-white p-5"><h2 className="font-bold">Credits per plan</h2><p className="text-xs text-(--color-text-muted)">Changes preserve credits already used by free members.</p><div className="mt-4 grid gap-3 sm:grid-cols-3">{[["free_credits","Free lifetime"],["weekly_credits","Pro weekly"],["annual_credits","Annual"]].map(([key,label]) => <label key={key} className="text-xs font-bold uppercase text-(--color-text-muted)">{label}<input type="number" min="0" className={input} value={values[key] ?? "0"} onChange={(e) => set(key, e.target.value)}/></label>)}</div></section>
    <section className="rounded-2xl border border-(--color-border) bg-white p-5"><h2 className="font-bold">Platform details</h2><div className="mt-4 grid gap-3 sm:grid-cols-2"><label className="text-xs font-bold uppercase text-(--color-text-muted)">Platform name<input className={input} value={values.platform_name ?? ""} onChange={(e) => set("platform_name", e.target.value)}/></label><label className="text-xs font-bold uppercase text-(--color-text-muted)">Support email<input type="email" className={input} value={values.support_email ?? ""} onChange={(e) => set("support_email", e.target.value)}/></label></div></section>
    <div className="flex items-center gap-3"><button onClick={save} className="inline-flex items-center gap-2 rounded-xl bg-(--color-burgundy) px-5 py-2.5 text-sm font-bold text-white"><Save size={16}/>Save settings</button><span className="text-sm text-(--color-text-muted)">{status}</span></div>
  </div>;
}
