import { Crown, Wallet, Users } from "lucide-react";
import { getSessionToken } from "@/lib/session";
import { apiClient } from "@/lib/api-client";
export const dynamic = "force-dynamic";
type Revenue = { paidUsers: number; estimatedMonthlyRevenue: number; byPlan: { plan: string; subscribers: number; estimatedMonthlyRevenue: number }[] };
export default async function RevenuePage() {
  const data = await apiClient.get<Revenue>("/api/admin/revenue", await getSessionToken());
  return <div><h1 className="text-2xl font-extrabold text-(--color-burgundy-dark)">Revenue &amp; Payouts</h1><p className="mb-6 mt-1 text-sm text-(--color-text-muted)">Subscription snapshot. Final settlements and fees remain authoritative in Polar.</p><div className="mb-6 grid gap-4 sm:grid-cols-2"><div className="rounded-2xl border border-(--color-border) bg-white p-5"><Users className="mb-3 text-(--color-burgundy)" size={20}/><p className="text-xs font-bold uppercase text-(--color-text-muted)">Paid users</p><p className="mt-1 text-3xl font-extrabold">{data.paidUsers}</p></div><div className="rounded-2xl border border-(--color-border) bg-white p-5"><Wallet className="mb-3 text-(--color-burgundy)" size={20}/><p className="text-xs font-bold uppercase text-(--color-text-muted)">Estimated monthly gross</p><p className="mt-1 text-3xl font-extrabold">${data.estimatedMonthlyRevenue.toFixed(2)}</p></div></div><div className="rounded-2xl border border-(--color-border) bg-white p-5"><h2 className="mb-4 font-bold">Plans</h2>{data.byPlan.length ? data.byPlan.map((row) => <div key={row.plan} className="flex items-center justify-between border-t border-(--color-border) py-3 first:border-0"><span className="flex items-center gap-2 font-semibold"><Crown size={15} className="text-amber-600"/>{row.plan.replaceAll("_", " ")}</span><span className="text-sm text-(--color-text-muted)">{row.subscribers} subscribers · ${row.estimatedMonthlyRevenue.toFixed(2)}/mo est.</span></div>) : <p className="text-sm text-(--color-text-muted)">No active paid subscriptions.</p>}</div></div>;
}
